const $=s=>document.querySelector(s);const state={books:[],current:null,chunks:[],index:0,speaking:false,paused:false,speed:1,timer:null,startedAt:0,resumeOffset:0,speechToken:0};
const els={library:$('#libraryView'),reader:$('#readerView'),grid:$('#bookGrid'),empty:$('#emptyState'),count:$('#bookCount'),text:$('#readerText'),title:$('#readerTitle'),meta:$('#readerMeta'),play:$('#playBtn'),progress:$('#progress'),percent:$('#percent'),elapsed:$('#elapsed'),remaining:$('#remaining'),toast:$('#toast')};
const mediaKeepalive={audio:null,active:false,start(){if(this.active)return;try{const rate=8000,size=8000,buffer=new ArrayBuffer(44+size),v=new DataView(buffer),str=(at,s)=>{for(let i=0;i<s.length;i++)v.setUint8(at+i,s.charCodeAt(i))};str(0,'RIFF');v.setUint32(4,36+size,true);str(8,'WAVE');str(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate,true);v.setUint16(32,1,true);v.setUint16(34,8,true);str(36,'data');v.setUint32(40,size,true);for(let i=0;i<size;i++)v.setUint8(44+i,128);let binary='';for(const byte of new Uint8Array(buffer))binary+=String.fromCharCode(byte);this.audio=new Audio('data:audio/wav;base64,'+btoa(binary));this.audio.loop=true;this.audio.volume=.01;this.audio.setAttribute('playsinline','');this.audio.play().then(()=>this.active=true).catch(()=>{this.audio=null})}catch{this.audio=null}},stop(){if(this.audio){this.audio.pause();this.audio.src='';this.audio=null}this.active=false}};
mediaKeepalive.pause=function(){this.audio?.pause()};mediaKeepalive.resume=function(){this.audio?.play().catch(()=>{})};
function toast(msg){els.toast.textContent=msg;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),2600)}
let libraryDb,saveTimer;function openLibraryDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open('slukhai-library',1);request.onupgradeneeded=()=>request.result.createObjectStore('data');request.onsuccess=()=>{libraryDb=request.result;resolve(libraryDb)};request.onerror=()=>reject(request.error)})}async function loadLibrary(){try{const db=await openLibraryDb(),stored=await new Promise((resolve,reject)=>{const request=db.transaction('data').objectStore('data').get('books');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});if(stored)state.books=stored;else{const legacy=JSON.parse(localStorage.getItem('books')||'[]');if(legacy.length){state.books=legacy;await persistLibrary();localStorage.removeItem('books')}}}catch(error){console.error(error);toast('Не вдалося відкрити сховище книжок')}renderLibrary()}async function persistLibrary(){try{const db=libraryDb||await openLibraryDb();await new Promise((resolve,reject)=>{const tx=db.transaction('data','readwrite');tx.objectStore('data').put(state.books,'books');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}catch(error){console.error(error);toast(error?.name==='QuotaExceededError'?'На пристрої недостатньо вільного місця для книжки':'Не вдалося зберегти бібліотеку')}}function save(){clearTimeout(saveTimer);saveTimer=setTimeout(persistLibrary,120)}
let activeCategory='all';function renderLibrary(){els.grid.innerHTML='';const categories=[...new Set(state.books.map(b=>b.category).filter(Boolean))];$('#categoryChips').innerHTML=categories.map(c=>`<button class="category-chip${activeCategory===c?' active':''}" data-category="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join('');document.querySelector('[data-category="all"]')?.classList.toggle('active',activeCategory==='all');document.querySelectorAll('.category-chip').forEach(chip=>chip.onclick=()=>{activeCategory=chip.dataset.category;renderLibrary()});const shown=state.books.map((b,i)=>({b,i})).filter(x=>activeCategory==='all'||x.b.category===activeCategory);els.empty.hidden=state.books.length>0;els.count.textContent=`${shown.length} ${shown.length===1?'книжка':'книжок'}`;shown.forEach(({b,i})=>{const node=document.createElement('article');node.className='book';const visual=b.cover?`<img src="${b.cover}" alt="Обкладинка ${escapeHtml(b.title)}">`:`<span>${b.type.toUpperCase()}</span><strong>${escapeHtml(b.title)}</strong>`;node.innerHTML=`<div class="cover">${visual}<span class="cover-progress">${b.progress||0}%</span><button class="delete-book" aria-label="Видалити книжку">×</button><button class="categorize-book" aria-label="Категорія">⋯</button></div><h3>${escapeHtml(b.title)}</h3><p>${escapeHtml(b.category||'Без категорії')} · ${b.chunks.length} уривків</p>`;node.onclick=()=>openBook(i);node.querySelector('.delete-book').onclick=e=>{e.stopPropagation();if(confirm(`Видалити «${b.title}»?`)){state.books.splice(i,1);save();renderLibrary();toast('Книжку видалено')}};node.querySelector('.categorize-book').onclick=e=>{e.stopPropagation();const category=prompt('Назва категорії:',b.category||'');if(category!==null){b.category=category.trim();save();renderLibrary()}};els.grid.append(node)})}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function chunkText(text){const clean=text.replace(/\r/g,'').replace(/\n{3,}/g,'\n\n').trim();const paras=clean.split(/\n\s*\n/).filter(Boolean);const chunks=[];for(const p of paras){if(p.length<900)chunks.push(p);else{const sentences=p.match(/[^.!?…]+[.!?…]+|[^.!?…]+$/g)||[p];let c='';for(const s of sentences){if((c+s).length>850&&c){chunks.push(c.trim());c=''}c+=s}if(c.trim())chunks.push(c.trim())}}return chunks}
let parsedChapters=[];async function parseFile(file){parsedChapters=[];const ext=file.name.split('.').pop().toLowerCase();if(ext==='txt'){const chunks=chunkText(await file.text());parsedChapters=[{title:'Текст',index:0}];return chunks}if(ext==='epub')return parseEpub(file);if(ext==='pdf'){const chunks=await parsePdf(file);parsedChapters=[{title:'PDF',index:0}];return chunks}throw Error('Непідтримуваний формат')}
async function epubToc(zip,opf,dir,items){const toc=new Map(),clean=s=>(s||'').split('#')[0],full=href=>decodeURIComponent(new URL(clean(href),'https://epub.local/'+dir).pathname.slice(1));try{const navItem=items.find(x=>(x.getAttribute('properties')||'').split(/\s+/).includes('nav'));if(navItem){const navPath=full(navItem.getAttribute('href')),entry=zip.file(navPath)||zip.file(dir+navItem.getAttribute('href'));if(entry){const doc=new DOMParser().parseFromString(await entry.async('text'),'text/html'),nav=doc.querySelector('nav[epub\\:type="toc"],nav[role="doc-toc"],nav');nav?.querySelectorAll('a[href]').forEach(a=>{const name=a.textContent.replace(/\s+/g,' ').trim();if(name)toc.set(full(a.getAttribute('href')),name)})}}const spine=opf.getElementsByTagName('spine')[0],ncxId=spine?.getAttribute('toc'),ncxItem=items.find(x=>x.getAttribute('id')===ncxId)||items.find(x=>x.getAttribute('media-type')==='application/x-dtbncx+xml');if(ncxItem){const ncxPath=full(ncxItem.getAttribute('href')),entry=zip.file(ncxPath)||zip.file(dir+ncxItem.getAttribute('href'));if(entry){const doc=new DOMParser().parseFromString(await entry.async('text'),'text/xml');[...doc.getElementsByTagName('navPoint')].forEach(point=>{const src=point.getElementsByTagName('content')[0]?.getAttribute('src'),name=point.getElementsByTagName('navLabel')[0]?.textContent.replace(/\s+/g,' ').trim();if(src&&name)toc.set(full(src),name)})}}}catch(error){console.warn('Не вдалося прочитати зміст EPUB',error)}return toc}
async function parseEpub(file){if(!window.JSZip)throw Error('Модуль EPUB ще не завантажився. Перевір інтернет і повтори.');const zip=await window.JSZip.loadAsync(file),container=await zip.file('META-INF/container.xml').async('text'),root=new DOMParser().parseFromString(container,'text/xml').getElementsByTagName('rootfile')[0]?.getAttribute('full-path');if(!root)throw Error('Не вдалося знайти структуру EPUB');const opfText=await zip.file(root).async('text'),opf=new DOMParser().parseFromString(opfText,'text/xml'),dir=root.includes('/')?root.slice(0,root.lastIndexOf('/')+1):'',items=[...opf.getElementsByTagName('item')],manifest={},toc=await epubToc(zip,opf,dir,items);items.forEach(x=>manifest[x.getAttribute('id')]=x.getAttribute('href'));const chunks=[];let number=1;for(const ref of [...opf.getElementsByTagName('itemref')]){const href=manifest[ref.getAttribute('idref')];if(!href)continue;const path=decodeURIComponent(new URL(href,'https://epub.local/'+dir).pathname.slice(1)),f=zip.file(path)||zip.file(dir+href);if(!f)continue;const doc=new DOMParser().parseFromString(await f.async('text'),'text/html');doc.querySelectorAll('script,style,nav,svg').forEach(x=>x.remove());const heading=(doc.querySelector('h1,h2,h3')?.textContent||'').replace(/\s+/g,' ').trim(),sectionChunks=chunkText(doc.body?.textContent||'');if(!sectionChunks.length)continue;const title=toc.get(path)||heading||`Розділ ${number}`;parsedChapters.push({title,index:chunks.length});number++;chunks.push(...sectionChunks)}if(!chunks.length)throw Error('У EPUB не знайдено текстових розділів');return chunks}
async function coverData(blob){return await new Promise(resolve=>{const url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const canvas=document.createElement('canvas'),ratio=Math.min(1,360/img.naturalWidth,540/img.naturalHeight);canvas.width=Math.max(1,Math.round(img.naturalWidth*ratio));canvas.height=Math.max(1,Math.round(img.naturalHeight*ratio));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);resolve(canvas.toDataURL('image/jpeg',.78))};img.onerror=()=>{URL.revokeObjectURL(url);resolve(null)};img.src=url})}
async function epubCover(file){try{const zip=await window.JSZip.loadAsync(file),container=await zip.file('META-INF/container.xml').async('text'),root=new DOMParser().parseFromString(container,'text/xml').getElementsByTagName('rootfile')[0]?.getAttribute('full-path');if(!root)return null;const opfText=await zip.file(root)?.async('text');if(!opfText)return null;const opf=new DOMParser().parseFromString(opfText,'text/xml'),dir=root.includes('/')?root.slice(0,root.lastIndexOf('/')+1):'',items=[...opf.getElementsByTagName('item')],metas=[...opf.getElementsByTagName('meta')],coverId=metas.find(x=>x.getAttribute('name')?.toLowerCase()==='cover')?.getAttribute('content');let item=items.find(x=>(x.getAttribute('properties')||'').split(/\s+/).includes('cover-image'))||items.find(x=>coverId&&x.getAttribute('id')===coverId)||items.find(x=>/cover|обклад/i.test(`${x.getAttribute('id')} ${x.getAttribute('href')}`)&&/^image\//.test(x.getAttribute('media-type')||''))||items.find(x=>/^image\//.test(x.getAttribute('media-type')||''));if(!item)return null;const href=item.getAttribute('href'),path=decodeURIComponent(new URL(href,'https://epub.local/'+dir).pathname.slice(1)),entry=zip.file(path)||zip.file(dir+href)||zip.file(decodeURIComponent(dir+href));if(!entry)return null;return await coverData(await entry.async('blob'))}catch(error){console.warn('Не вдалося прочитати обкладинку EPUB',error);return null}}
async function parsePdf(file){const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;let text='';for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),content=await page.getTextContent();text+='\n\n'+content.items.map(x=>x.str).join(' ')}return chunkText(text)}
$('#bookInput').onchange=async e=>{const files=[...e.target.files];if(!files.length)return;let added=0;for(const file of files){toast(`Опрацьовую ${added+1} із ${files.length}…`);try{const chunks=await parseFile(file);if(!chunks.length)throw Error('У файлі не знайдено тексту');const cover=file.name.toLowerCase().endsWith('.epub')?await epubCover(file):null;state.books.unshift({title:file.name.replace(/\.[^.]+$/,''),type:file.name.split('.').pop(),chunks,chapters:[...parsedChapters],cover,progress:0,index:0,added:Date.now()});added++}catch(err){toast(err?.name==='QuotaExceededError'?'На пристрої недостатньо вільного місця':`Не вдалося додати «${file.name}»: ${err.message||'невідома помилка'}`)}}await persistLibrary();renderLibrary();toast(`Додано книжок: ${added}`);e.target.value=''};
function openBook(i){state.current=i;const b=state.books[i];state.chunks=b.chunks;state.index=b.index||0;state.resumeOffset=b.offset||0;els.title.textContent=b.title;els.library.classList.remove('active');els.reader.classList.add('active');renderReader()}
function updateMediaSession(){if(!('mediaSession'in navigator)||state.current===null)return;const b=state.books[state.current];navigator.mediaSession.metadata=new MediaMetadata({title:b.title,artist:'Слухай · українська читалка',album:`Уривок ${state.index+1} із ${b.chunks.length}`,artwork:[{src:new URL('./icon.svg',location.href).href,sizes:'512x512',type:'image/svg+xml'}]});navigator.mediaSession.playbackState=state.speaking?'playing':'paused'}
function words(s){return (s.match(/[\p{L}\p{N}]+/gu)||[]).length}function clock(seconds){seconds=Math.max(0,Math.round(seconds));const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
function timing(extra=0){const totalWords=state.chunks.reduce((n,c)=>n+words(c),0),doneWords=state.chunks.slice(0,state.index).reduce((n,c)=>n+words(c),0),current=state.chunks[state.index]||'',fraction=Math.min(1,(state.resumeOffset||0)/Math.max(1,current.length));const total=totalWords/(155*state.speed)*60,done=(doneWords+words(current)*fraction)/(155*state.speed)*60+extra;els.elapsed.textContent=clock(done);els.remaining.textContent='−'+clock(total-done)}
const pageState={pages:[],page:0,text:''};function spreadSize(){return document.body.dataset.readerMode==='pages'&&window.innerWidth>=900&&$('#desktopSpread')?.checked?2:1}function paginate(text){if(document.body.dataset.readerMode!=='pages')return[text];const size=Number($('#fontSize').value)||21,spread=spreadSize(),available=Math.min(spread===2?1240:760,window.innerWidth-44),width=Math.max(240,spread===2?(available-64)/2:available),hidden=document.body.classList.contains('chrome-hidden'),height=Math.max(180,hidden?window.innerHeight-118:window.innerHeight-318),mobileFactor=window.innerWidth<900?.68:1,chars=Math.max(120,Math.floor(width/(size*.52)*height/(size*1.72)*mobileFactor)),words=text.split(/\s+/),pages=[];let page='';for(const word of words){if(page.length+word.length+1>chars&&page){pages.push(page);page=''}page+=(page?' ':'')+word}if(page)pages.push(page);return pages.length?pages:['']}
function displayPage(direction=0){const spread=spreadSize(),start=spread===2?Math.floor(pageState.page/2)*2:pageState.page;pageState.page=start;els.text.classList.toggle('two-page-spread',spread===2);els.text.innerHTML=Array.from({length:spread},(_,offset)=>{const at=start+offset,text=pageState.pages[at];return text===undefined?'':`<p class="book-page" data-page="${at}">${escapeHtml(text)}</p>`}).join('');els.text.scrollTop=0;const b=state.books[state.current],chapter=[...(b.chapters||[])].reverse().find(x=>x.index<=state.index),last=Math.min(pageState.pages.length,start+spread);els.meta.textContent=`${chapter?.title?chapter.title+' · ':''}${state.index+1}/${state.chunks.length}${pageState.pages.length>1?` · стор. ${start+1}${last>start+1?'–'+last:''}/${pageState.pages.length}`:''}`;els.text.classList.remove('turn-forward','turn-back');void els.text.offsetWidth;if(direction)els.text.classList.add(direction>0?'turn-forward':'turn-back')}
function setPageText(text){pageState.text=text;pageState.pages=paginate(text);pageState.page=0;displayPage()}
function repaginate(){if(state.current===null||document.body.dataset.readerMode!=='pages'||!pageState.text)return;const ratio=pageState.pages.length>1?pageState.page/(pageState.pages.length-1):0;pageState.pages=paginate(pageState.text);pageState.page=Math.min(pageState.pages.length-1,Math.round(ratio*Math.max(0,pageState.pages.length-1)));displayPage()}
function turnPage(delta){if(document.body.dataset.readerMode==='pages'){const next=pageState.page+delta*spreadSize();if(next>=0&&next<pageState.pages.length){pageState.page=next;displayPage(delta);return}}stop();state.resumeOffset=0;state.books[state.current].offset=0;state.index=Math.max(0,Math.min(state.chunks.length-1,state.index+delta));renderReader();displayPage(delta)}
function renderReader(){const b=state.books[state.current],total=state.chunks.length,current=state.chunks[state.index]||'',fraction=Math.min(1,(state.resumeOffset||0)/Math.max(1,current.length)),p=Math.round(((state.index+fraction)/Math.max(1,total))*100);setPageText(current);els.progress.value=p;els.percent.textContent=p+'%';b.index=state.index;b.progress=p;save();timing();updateMediaSession();if($('#showTranslation')?.checked)showPageTranslation(state.index)}
async function showPageTranslation(index){try{const value=await translated(state.chunks[index]);if(index===state.index&&$('#showTranslation').checked)setPageText(value)}catch{}}
function applyPronunciation(text){const lines=$('#pronunciation').value.split('\n');for(const line of lines){const at=line.indexOf('=');if(at<1)continue;const from=line.slice(0,at).trim(),to=line.slice(at+1).trim();if(from&&to)text=text.replaceAll(from,to)}return text}
function highlightWord(text,start,length){const p=els.text.querySelector('p');if(!p)return;if(document.body.dataset.readerMode==='pages'){const pages=paginate(text);let offset=0,pageIndex=0;for(let i=0;i<pages.length;i++){const end=offset+pages[i].length;if(start<=end){pageIndex=i;break}offset=end+1}pageState.text=text;pageState.pages=pages;pageState.page=pageIndex;const page=pages[pageIndex]||'',local=Math.max(0,Math.min(page.length,start-offset)),wordEnd=Math.min(page.length,local+Math.max(length,1));p.innerHTML=`${escapeHtml(page.slice(0,local))}<mark>${escapeHtml(page.slice(local,wordEnd))}</mark>${escapeHtml(page.slice(wordEnd))}`;return}const end=Math.min(text.length,start+Math.max(length,1));p.innerHTML=`${escapeHtml(text.slice(0,start))}<mark>${escapeHtml(text.slice(start,end))}</mark>${escapeHtml(text.slice(end))}`;p.querySelector('mark')?.scrollIntoView({block:'center',behavior:'smooth'})}
function nativeTTS(){return window.Capacitor?.Plugins?.TextToSpeech}function stop(){state.speechToken++;speechSynthesis.cancel();nativeTTS()?.stop?.();mediaKeepalive.stop();clearInterval(state.timer);state.timer=null;state.speaking=false;state.paused=false;els.play.textContent='▶';updateMediaSession();save()}
function pausePlayback(){if(!state.speaking)return;speechSynthesis.pause();mediaKeepalive.pause();clearInterval(state.timer);state.timer=null;state.speaking=false;state.paused=true;els.play.textContent='▶';updateMediaSession();save()}
function resumePlayback(){if(!state.paused)return;mediaKeepalive.resume();speechSynthesis.resume();state.paused=false;state.speaking=true;state.startedAt=Date.now();els.play.textContent='❚❚';state.timer=setInterval(()=>timing((Date.now()-state.startedAt)/1000),1000);updateMediaSession()}
function skipFromMedia(delta){stop();state.paused=false;state.resumeOffset=0;state.books[state.current].offset=0;state.index=Math.max(0,Math.min(state.chunks.length-1,state.index+delta));renderReader();mediaKeepalive.start();speak()}
async function googleTranslate(text,target){const parts=text.match(/[\s\S]{1,450}(?:\s|$)/g)||[text],out=[];for(const part of parts){const url=`https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=${target}&dt=t&q=`+encodeURIComponent(part);const r=await fetch(url);if(!r.ok)throw Error();const data=await r.json();out.push(data[0].map(x=>x[0]).join(''))}return out.join(' ')}
async function translated(text){if(!$('#translateToggle').checked)return text;const book=state.books[state.current],target=$('#speechLanguage').value.split('-')[0],key=`${state.index}:${target}`;book.translations=book.translations||{};if(book.translations[key])return book.translations[key];toast('Перекладаю мовою озвучення…');const endpoint=$('#translateEndpoint').value.trim();try{let result;if(endpoint){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({q:text,source:'auto',target,format:'text'})});if(!r.ok)throw Error();result=(await r.json()).translatedText}else result=await googleTranslate(text,target);book.translations[key]=result;save();return result}catch{toast('Не вдалося перекласти. Перевір з’єднання або сервіс.');throw Error('translation_failed')}}
async function speak(resuming=false){if(state.speaking&&!resuming){stop();return}if(!nativeTTS()&&!('speechSynthesis'in window)){toast('Цей пристрій не підтримує озвучення');return}let text;try{text=applyPronunciation(await translated(state.chunks[state.index]))}catch{return}els.text.innerHTML=`<p>${escapeHtml(text)}</p>`;const base=Math.min(state.resumeOffset||0,text.length),token=++state.speechToken;if(nativeTTS()){state.speaking=true;state.startedAt=Date.now();els.play.textContent='❚❚';updateMediaSession();state.timer=setInterval(()=>timing((Date.now()-state.startedAt)/1000),1000);try{await nativeTTS().speak({text:text.slice(base),lang:$('#speechLanguage').value,rate:state.speed,pitch:Number($('#voicePitch').value),category:'playback'});if(token!==state.speechToken)return;clearInterval(state.timer);state.speaking=false;state.resumeOffset=0;state.books[state.current].offset=0;if(state.index<state.chunks.length-1){state.index++;renderReader();speak()}}catch{if(token===state.speechToken)stop()}return}const u=new SpeechSynthesisUtterance(text.slice(base));u.lang=$('#speechLanguage').value;u.rate=state.speed;u.pitch=Number($('#voicePitch').value);const voice=speechSynthesis.getVoices().find(v=>v.name===$('#voiceSelect').value);if(voice){u.voice=voice;u.lang=voice.lang}u.onboundary=e=>{if(token!==state.speechToken)return;state.resumeOffset=base+e.charIndex;highlightWord(text,state.resumeOffset,e.charLength||text.slice(state.resumeOffset).search(/\s|$/));const book=state.books[state.current];book.offset=state.resumeOffset;book.index=state.index;save()};u.onstart=()=>{if(token!==state.speechToken)return;state.speaking=true;state.startedAt=Date.now();els.play.textContent='❚❚';updateMediaSession();els.text.querySelector('p').classList.add('speaking');clearInterval(state.timer);state.timer=setInterval(()=>timing((Date.now()-state.startedAt)/1000),1000)};u.onend=()=>{if(token!==state.speechToken)return;clearInterval(state.timer);state.timer=null;state.speaking=false;els.play.textContent='▶';state.resumeOffset=0;state.books[state.current].offset=0;updateMediaSession();if(state.index<state.chunks.length-1){state.index++;renderReader();speak()}};u.onerror=e=>{if(e.error!=='canceled'&&token===state.speechToken)stop()};speechSynthesis.speak(u)}
els.play.onclick=()=>{if(state.paused)resumePlayback();else if(state.speaking)pausePlayback();else{mediaKeepalive.start();speak()}};$('#prevBtn').onclick=()=>turnPage(-1);$('#nextBtn').onclick=()=>turnPage(1);els.progress.onchange=e=>{stop();state.resumeOffset=0;state.books[state.current].offset=0;state.index=Math.round((+e.target.value/100)*(state.chunks.length-1));renderReader()};
function showLibrary(){if(state.current!==null)stop();els.reader.classList.remove('active');els.library.classList.add('active');state.current=null;renderLibrary();window.scrollTo(0,0)}$('#backBtn').onclick=showLibrary;$('.brand').onclick=e=>{e.preventDefault();showLibrary()};$('#speedBtn').onclick=e=>{const speeds=[.75,1,1.25,1.5,2],wasSpeaking=state.speaking;state.speed=speeds[(speeds.indexOf(state.speed)+1)%speeds.length];e.target.textContent=state.speed+'×';timing();if(wasSpeaking){state.speechToken++;speechSynthesis.cancel();clearInterval(state.timer);state.timer=null;state.speaking=false;setTimeout(()=>speak(true),40)}};
const dialog=$('#settingsDialog');$('#translateToggle').checked=localStorage.getItem('autoTranslate')!=='false';$('#translateEndpoint').value=localStorage.getItem('translateEndpoint')||'';$('#voicePitch').value=localStorage.getItem('voicePitch')||'1';$('#speechLanguage').value=localStorage.getItem('speechLanguage')||'uk-UA';$('#fontSize').value=localStorage.getItem('fontSize')||'21';$('#fontSizeValue').textContent=$('#fontSize').value+' px';document.documentElement.style.setProperty('--reader-size',$('#fontSize').value+'px');$('#translateToggle').onchange=e=>localStorage.setItem('autoTranslate',e.target.checked);$('#translateEndpoint').onchange=e=>localStorage.setItem('translateEndpoint',e.target.value.trim());$('#voicePitch').onchange=e=>localStorage.setItem('voicePitch',e.target.value);$('#voiceSelect').onchange=e=>localStorage.setItem('voiceName',e.target.value);$('#speechLanguage').onchange=e=>{localStorage.setItem('speechLanguage',e.target.value);localStorage.removeItem('voiceName');voices()};$('#settingsBtn').onclick=()=>dialog.showModal();$('#readerSettingsBtn').onclick=()=>dialog.showModal();$('#fontSize').oninput=e=>{localStorage.setItem('fontSize',e.target.value);$('#fontSizeValue').textContent=e.target.value+' px';document.documentElement.style.setProperty('--reader-size',e.target.value+'px');if(state.current!==null)renderReader()};function voices(){const language=$('#speechLanguage').value.toLowerCase(),base=language.split('-')[0],all=speechSynthesis.getVoices().filter(v=>v.lang.toLowerCase().split('-')[0]===base).sort((a,b)=>Number(b.localService)-Number(a.localService)||a.name.localeCompare(b.name)),saved=localStorage.getItem('voiceName');$('#voiceSelect').innerHTML=all.map(v=>`<option value="${escapeHtml(v.name)}"${v.name===saved?' selected':''}>${escapeHtml(v.name)} — ${escapeHtml(v.lang)}${v.localService?' · на пристрої':' · мережевий'}</option>`).join('')||'<option value="">Системний голос для цієї мови</option>';$('#voiceHint').textContent=all.length?`Доступно голосів: ${all.length}`:'Окремого голосу немає — браузер використає системний'}voices();speechSynthesis.onvoiceschanged=voices;
$('#pronunciation').value=localStorage.getItem('pronunciation')||'';$('#pronunciation').onchange=e=>localStorage.setItem('pronunciation',e.target.value);
const readerSettingsDialog=$('#readerSettingsDialog');$('#readerSettingsBtn').onclick=()=>readerSettingsDialog.showModal();$('#desktopSpread').checked=localStorage.getItem('desktopSpread')!=='false';$('#desktopSpread').onchange=e=>{localStorage.setItem('desktopSpread',e.target.checked);if(state.current!==null)repaginate()};
const fontMap={serif:'"Source Serif 4",Georgia,serif',system:'Manrope,system-ui,sans-serif',dyslexic:'Arial,Verdana,sans-serif'};function applyReaderPrefs(){$('#fontFamily').value=localStorage.getItem('fontFamily')||'serif';$('#readerTheme').value=localStorage.getItem('readerTheme')||'paper';$('#readerMode').value=localStorage.getItem('readerMode')||'pages';$('#showTranslation').checked=localStorage.getItem('showTranslation')==='true';document.documentElement.style.setProperty('--reader-font',fontMap[$('#fontFamily').value]);document.body.dataset.theme=$('#readerTheme').value;document.body.dataset.readerMode=$('#readerMode').value}applyReaderPrefs();$('#fontFamily').onchange=e=>{localStorage.setItem('fontFamily',e.target.value);document.documentElement.style.setProperty('--reader-font',fontMap[e.target.value]);if(state.current!==null)renderReader()};$('#readerTheme').onchange=e=>{localStorage.setItem('readerTheme',e.target.value);document.body.dataset.theme=e.target.value};$('#readerMode').onchange=e=>{localStorage.setItem('readerMode',e.target.value);document.body.dataset.readerMode=e.target.value;if(state.current!==null)renderReader()};$('#showTranslation').onchange=e=>{localStorage.setItem('showTranslation',e.target.checked);if(state.current!==null)renderReader()};els.text.addEventListener('click',e=>{if(document.body.dataset.readerMode!=='pages')return;const x=e.clientX/window.innerWidth;if(x<.28)turnPage(-1);else if(x>.72)turnPage(1);else document.body.classList.toggle('chrome-hidden')});
$('#exportBackup').onclick=async()=>{await persistLibrary();const settings={};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);settings[key]=localStorage.getItem(key)}const blob=new Blob([JSON.stringify({version:1,createdAt:new Date().toISOString(),books:state.books,settings})],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`slukhai-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('#importBackup').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.books))throw Error();state.books=data.books;for(const[key,value]of Object.entries(data.settings||{}))localStorage.setItem(key,value);await persistLibrary();toast('Backup успішно відновлено');setTimeout(()=>location.reload(),700)}catch{toast('Не вдалося імпортувати backup: неправильний файл')}e.target.value=''};
const pageDrag={active:false,startX:0,lastX:0,startTime:0,moved:false,suppressClick:false};els.text.addEventListener('pointerdown',e=>{if(document.body.dataset.readerMode!=='pages'||e.pointerType==='mouse'&&e.button!==0)return;pageDrag.active=true;pageDrag.startX=pageDrag.lastX=e.clientX;pageDrag.startTime=Date.now();pageDrag.moved=false;els.text.setPointerCapture?.(e.pointerId);els.text.classList.add('dragging')});els.text.addEventListener('pointermove',e=>{if(!pageDrag.active)return;const dx=e.clientX-pageDrag.startX;pageDrag.lastX=e.clientX;if(Math.abs(dx)>8)pageDrag.moved=true;const progress=Math.min(1,Math.abs(dx)/window.innerWidth),angle=(dx<0?-1:1)*progress*12;els.text.style.transform=`translateX(calc(-50% + ${dx}px)) rotateY(${angle}deg)`;els.text.style.opacity=String(1-progress*.35)});function finishPageDrag(e){if(!pageDrag.active)return;pageDrag.active=false;els.text.releasePointerCapture?.(e.pointerId);els.text.classList.remove('dragging');const dx=pageDrag.lastX-pageDrag.startX,velocity=Math.abs(dx)/Math.max(1,Date.now()-pageDrag.startTime);pageDrag.suppressClick=pageDrag.moved;els.text.style.transform='';els.text.style.opacity='';if(Math.abs(dx)>window.innerWidth*.2||velocity>.55)turnPage(dx<0?1:-1);setTimeout(()=>pageDrag.suppressClick=false,80)}els.text.addEventListener('pointerup',finishPageDrag);els.text.addEventListener('pointercancel',finishPageDrag);els.text.addEventListener('click',e=>{if(pageDrag.suppressClick){e.preventDefault();e.stopImmediatePropagation()}},true);
els.text.addEventListener('click',e=>{const x=e.clientX/window.innerWidth;if(document.body.dataset.readerMode==='pages'&&x>=.28&&x<=.72&&!pageDrag.suppressClick)setTimeout(repaginate,0)});let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(repaginate,120)});

const bookDialog=$('#bookDialog'),toolContent=$('#toolContent');let activeTool='toc';function jumpTo(index){stop();state.index=index;state.resumeOffset=0;state.books[state.current].offset=0;bookDialog.close();renderReader()}function renderTools(){const b=state.books[state.current];$('.tool-tabs .active')?.classList.remove('active');$(`#${activeTool}Tab`).classList.add('active');if(activeTool==='toc'){let points=b.chapters?.length?b.chapters:b.chunks.filter((_,i)=>i%50===0).map((text,j)=>({title:`Частина ${j+1}`,index:j*50}));toolContent.innerHTML=points.map((x,n)=>`<button class="tool-item" data-jump="${x.index}"><span>${escapeHtml(x.title||`Розділ ${n+1}`)}</span><small>${Math.round(x.index/b.chunks.length*100)}%</small></button>`).join('')}else if(activeTool==='bookmarks'){const marks=b.bookmarks||[];toolContent.innerHTML=marks.length?marks.map(i=>`<button class="tool-item" data-jump="${i}"><span>${escapeHtml(b.chunks[i].slice(0,75))}</span><small>${i+1}</small></button>`).join(''):'<p class="hint">Закладок ще немає.</p>'}else{b.notes=b.notes||{};toolContent.innerHTML=`<textarea class="note-box" id="currentNote" placeholder="Нотатка до цього уривка…">${escapeHtml(b.notes[state.index]||'')}</textarea><button class="primary-button full" id="saveNote">Зберегти нотатку</button>`;$('#saveNote').onclick=()=>{b.notes[state.index]=$('#currentNote').value;save();toast('Нотатку збережено')}}toolContent.querySelectorAll('[data-jump]').forEach(x=>x.onclick=()=>jumpTo(Number(x.dataset.jump)))}$('#contentsBtn').onclick=()=>{activeTool='toc';renderTools();bookDialog.showModal()};$('#closeBookDialog').onclick=()=>bookDialog.close();$('#tocTab').onclick=()=>{activeTool='toc';renderTools()};$('#bookmarksTab').onclick=()=>{activeTool='bookmarks';renderTools()};$('#notesTab').onclick=()=>{activeTool='notes';renderTools()};$('#bookmarkBtn').onclick=()=>{const b=state.books[state.current];b.bookmarks=b.bookmarks||[];const at=b.bookmarks.indexOf(state.index);if(at>=0){b.bookmarks.splice(at,1);$('#bookmarkBtn').textContent='☆';toast('Закладку прибрано')}else{b.bookmarks.push(state.index);$('#bookmarkBtn').textContent='★';toast('Закладку додано')}save()};

let sleepTimer=null,sleepEnds=0;const sleepDialog=$('#sleepDialog');$('#sleepBtn').onclick=()=>sleepDialog.showModal();$('#closeSleepDialog').onclick=()=>sleepDialog.close();document.querySelectorAll('[data-minutes]').forEach(button=>button.onclick=()=>{clearTimeout(sleepTimer);const minutes=Number(button.dataset.minutes);if(minutes){sleepEnds=Date.now()+minutes*60000;sleepTimer=setTimeout(()=>{stop();toast('Таймер сну завершив відтворення')},minutes*60000);$('#sleepStatus').textContent=`Зупинка через ${minutes} хв`;$('#sleepBtn').textContent='◔'}else{sleepEnds=0;$('#sleepStatus').textContent='Таймер вимкнено';$('#sleepBtn').textContent='☾'}sleepDialog.close()});
$('#pageAnimation').value=localStorage.getItem('pageAnimation')||'slide';document.body.dataset.pageAnimation=$('#pageAnimation').value;$('#pageAnimation').onchange=e=>{localStorage.setItem('pageAnimation',e.target.value);document.body.dataset.pageAnimation=e.target.value};
setTimeout(()=>$('#appSplash')?.classList.add('done'),850);
$('#setCustomSleep').onclick=()=>{const minutes=Number($('#customSleepMinutes').value);if(!Number.isFinite(minutes)||minutes<1||minutes>720){toast('Вкажи час від 1 до 720 хвилин');return}clearTimeout(sleepTimer);sleepEnds=Date.now()+minutes*60000;sleepTimer=setTimeout(()=>{stop();sleepEnds=0;$('#sleepBtn').textContent='☾';toast('Таймер сну завершив відтворення')},minutes*60000);$('#sleepStatus').textContent=`Зупинка через ${minutes} хв`;$('#sleepBtn').textContent='◔';sleepDialog.close()};document.addEventListener('visibilitychange',()=>{if(!document.hidden&&sleepEnds&&Date.now()>=sleepEnds){clearTimeout(sleepTimer);sleepEnds=0;stop();$('#sleepBtn').textContent='☾';toast('Таймер сну завершив відтворення')}});
const aboutDialog=$('#aboutDialog'),supportUrl=window.SLUKHAI_CONFIG?.supportUrl?.trim(),supportLabel=window.SLUKHAI_CONFIG?.supportLabel||'Підтримати проєкт';$('#aboutAppBtn').onclick=()=>{dialog.close();aboutDialog.showModal()};$('#closeAboutDialog').onclick=()=>aboutDialog.close();function openSupport(){if(supportUrl)window.open(supportUrl,'_blank','noopener,noreferrer')}for(const button of [$('#supportProject'),$('#supportFromAbout')]){if(supportUrl){button.hidden=false;button.textContent='♡ '+supportLabel;button.onclick=openSupport}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw-v2.js');loadLibrary();
if('mediaSession'in navigator){navigator.mediaSession.setActionHandler('play',()=>state.paused?resumePlayback():els.play.click());navigator.mediaSession.setActionHandler('pause',()=>pausePlayback());navigator.mediaSession.setActionHandler('previoustrack',()=>skipFromMedia(-1));navigator.mediaSession.setActionHandler('nexttrack',()=>skipFromMedia(1));navigator.mediaSession.setActionHandler('seekbackward',()=>skipFromMedia(-1));navigator.mediaSession.setActionHandler('seekforward',()=>skipFromMedia(1))}
// Пошук у бібліотеці застосовується поверх активної категорії без зміни даних книжок.
let librarySearchQuery='';
const renderLibraryBase=renderLibrary;
renderLibrary=function(){
  renderLibraryBase();
  const query=librarySearchQuery.trim().toLocaleLowerCase('uk');
  let visible=0;
  document.querySelectorAll('#bookGrid .book').forEach(card=>{
    const matches=!query||(card.querySelector('h3')?.textContent||'').toLocaleLowerCase('uk').includes(query);
    card.hidden=!matches;
    if(matches)visible++;
    const categoryButton=card.querySelector('.categorize-book');
    if(categoryButton){categoryButton.textContent='🏷';categoryButton.title='Змінити категорію'}
  });
  els.count.textContent=`${visible} ${visible===1?'книжка':'книжок'}`;
};
$('#bookSearch')?.addEventListener('input',event=>{librarySearchQuery=event.target.value;renderLibrary()});
renderLibrary();

const installDialog=$('#installDialog'),isInstalledPwa=window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;
if(isInstalledPwa)$('#installHelpHome').hidden=true;
function showInstallHelp(){dialog.close();installDialog.showModal()}
$('#installHelpHome').onclick=showInstallHelp;
$('#installHelpSettings').onclick=showInstallHelp;
$('#closeInstallDialog').onclick=()=>installDialog.close();
$('#closeInstallDialogBottom').onclick=()=>installDialog.close();
window.addEventListener('appinstalled',()=>{$('#installHelpHome').hidden=true;installDialog.close();toast('«Слухай» установлено')});

highlightWord=function(text,start,length){
  if(document.body.dataset.readerMode==='pages'){
    const pages=paginate(text);let offset=0,pageIndex=0;
    for(let i=0;i<pages.length;i++){const end=offset+pages[i].length;if(start<=end){pageIndex=i;break}offset=end+1}
    pageState.text=text;pageState.pages=pages;pageState.page=spreadSize()===2?Math.floor(pageIndex/2)*2:pageIndex;displayPage();
    if(spreadSize()===2){const target=els.text.querySelector(`[data-chunk="${state.index}"]`),end=Math.min(text.length,start+Math.max(length,1));if(target)target.innerHTML=`${escapeHtml(text.slice(0,start))}<mark>${escapeHtml(text.slice(start,end))}</mark>${escapeHtml(text.slice(end))}`;return}
    const page=pages[pageIndex]||'',local=Math.max(0,Math.min(page.length,start-offset)),wordEnd=Math.min(page.length,local+Math.max(length,1)),target=els.text.querySelector(`[data-page="${pageIndex}"]`);
    if(target)target.innerHTML=`${escapeHtml(page.slice(0,local))}<mark>${escapeHtml(page.slice(local,wordEnd))}</mark>${escapeHtml(page.slice(wordEnd))}`;
    return;
  }
  const p=els.text.querySelector('p');if(!p)return;const end=Math.min(text.length,start+Math.max(length,1));p.innerHTML=`${escapeHtml(text.slice(0,start))}<mark>${escapeHtml(text.slice(start,end))}</mark>${escapeHtml(text.slice(end))}`;p.querySelector('mark')?.scrollIntoView({block:'center',behavior:'smooth'});
};

$('#updateAppBtn').onclick=async event=>{
  const button=event.currentTarget,original=button.textContent;
  button.disabled=true;button.textContent='Оновлюю…';
  try{
    await persistLibrary();
    if(!navigator.onLine)throw Error('offline');
    const registrations='serviceWorker'in navigator?await navigator.serviceWorker.getRegistrations():[];
    await Promise.all(registrations.map(registration=>registration.unregister()));
    if('caches'in window)await Promise.all((await caches.keys()).filter(name=>name.startsWith('slukhai-')).map(name=>caches.delete(name)));
    const url=new URL(location.href);url.searchParams.set('update',Date.now());url.hash='';
    location.replace(url.href);
  }catch(error){
    console.error(error);toast('Не вдалося оновити. Перевір інтернет і повтори.');
    button.disabled=false;button.textContent=original;
  }
};

// Настільний розворот заповнює обидві сторінки кількома послідовними уривками.
const displayPageBase=displayPage,turnPageBase=turnPage;
displayPage=function(direction=0){
  if(spreadSize()!==2||state.current===null){displayPageBase(direction);return}
  const probe=paginate('слово '.repeat(5000)),capacity=Math.max(700,Math.floor((probe[0]?.length||1200)*.98)),validStart=Number.isInteger(pageState.desktopStart)&&state.index>=pageState.desktopStart&&state.index<pageState.desktopEnd,spreadStart=validStart?pageState.desktopStart:state.index,leaves=[];let cursor=spreadStart;
  for(let leaf=0;leaf<2;leaf++){
    const parts=[];let used=0;
    while(cursor<state.chunks.length){const part=state.chunks[cursor],cost=part.length+(parts.length?2:0);if(parts.length&&used+cost>capacity)break;parts.push({text:part,index:cursor});used+=cost;cursor++;if(used>=capacity*.88)break}
    leaves.push(parts);
  }
  pageState.desktopStart=spreadStart;pageState.desktopEnd=cursor;pageState.desktopAdvance=Math.max(1,cursor-spreadStart);pageState.desktopHistory=pageState.desktopHistory||[];
  const b=state.books[state.current],targetLanguage=$('#speechLanguage').value.split('-')[0],allParts=leaves.flat();els.text.classList.add('two-page-spread');els.text.innerHTML=`<div class="spread-flow">${allParts.map(part=>{const shown=$('#showTranslation')?.checked?(b.translations?.[`${part.index}:${targetLanguage}`]||part.text):part.text;return`<p data-chunk="${part.index}">${escapeHtml(shown)}</p>`}).join('')}</div>`;
  // Переклад виконується послідовно під час озвучення. Масовий переклад усього
  // розвороту перевантажує локальну модель на комп'ютерах і мобільних пристроях.
  const chapter=[...(b.chapters||[])].reverse().find(x=>x.index<=state.index);els.meta.textContent=`${chapter?.title?chapter.title+' · ':''}${spreadStart+1}–${Math.min(state.chunks.length,cursor)}/${state.chunks.length}`;
  els.text.classList.remove('turn-forward','turn-back');void els.text.offsetWidth;if(direction)els.text.classList.add(direction>0?'turn-forward':'turn-back');
};
turnPage=function(delta){
  if(document.body.dataset.readerMode==='pages'&&spreadSize()===2){
    stop();state.resumeOffset=0;state.books[state.current].offset=0;pageState.desktopHistory=pageState.desktopHistory||[];
    if(delta>0){pageState.desktopHistory.push(pageState.desktopStart??state.index);state.index=Math.min(state.chunks.length-1,pageState.desktopEnd??state.index+(pageState.desktopAdvance||1));pageState.desktopStart=null}
    else{state.index=pageState.desktopHistory.length?pageState.desktopHistory.pop():Math.max(0,state.index-2);pageState.desktopStart=null}
    renderReader();displayPage(delta);return;
  }
  turnPageBase(delta);
};
document.addEventListener('keydown',event=>{
  if(state.current===null||dialog.open||readerSettingsDialog.open||bookDialog.open||sleepDialog.open||installDialog.open)return;
  if(event.target.closest('input,textarea,select,button'))return;
  if(event.key==='ArrowRight'||event.key==='PageDown'){event.preventDefault();turnPage(1)}
  if(event.key==='ArrowLeft'||event.key==='PageUp'){event.preventDefault();turnPage(-1)}
  if(event.code==='Space'){event.preventDefault();els.play.click()}
});
els.text.addEventListener('click',event=>{if(window.getSelection()?.toString().trim()){event.stopImmediatePropagation()}},true);
document.addEventListener('gesturestart',event=>event.preventDefault(),{passive:false});

async function translateVisibleSpread(parts,book,target){book.translations=book.translations||{};for(const part of parts){const key=`${part.index}:${target}`;try{if(target==='uk'&&isProbablyUkrainian(part.text)){delete book.translations[key];continue}if(!book.translations[key])book.translations[key]=await googleTranslate(part.text,target);const node=els.text.querySelector(`[data-chunk="${part.index}"]`);if(node&&part.index!==state.index)node.textContent=book.translations[key]}catch(error){console.warn('Не вдалося перекласти видимий уривок',error)}}save()}

const OFFLINE_MODEL='Xenova/opus-mt-en-uk';let offlineTranslator=null,offlineLoading=null;
const offlineStatus=$('#offlinePackStatus'),offlineButton=$('#downloadOfflinePack'),offlineToggle=$('#offlineTranslateToggle');
offlineToggle.checked=localStorage.getItem('offlineTranslate')==='true';
function updateOfflinePackUi(){const ready=localStorage.getItem('offlineEnUkReady')==='true';offlineStatus.textContent=ready?'Завантажено · готовий до роботи без інтернету':'Пакет не завантажено · приблизно 120–180 МБ';offlineButton.textContent=ready?'Перевірити пакет':'Завантажити'}
updateOfflinePackUi();offlineToggle.onchange=e=>localStorage.setItem('offlineTranslate',e.target.checked);
async function loadOfflineTranslator(showProgress=false){
  if(offlineTranslator)return offlineTranslator;if(offlineLoading)return offlineLoading;
  offlineLoading=(async()=>{offlineButton.disabled=true;offlineStatus.classList.add('offline-progress');try{const {pipeline,env}=await import('https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1');env.useBrowserCache=true;offlineTranslator=await pipeline('translation',OFFLINE_MODEL,{dtype:'q8',progress_callback:data=>{if(!showProgress||typeof data.progress!=='number')return;const progress=Math.max(0,Math.min(100,Math.round(data.progress)));offlineStatus.style.setProperty('--download-progress',progress+'%');offlineStatus.textContent=`Завантаження мовного пакета: ${progress}%`}});localStorage.setItem('offlineEnUkReady','true');offlineToggle.checked=true;localStorage.setItem('offlineTranslate','true');offlineStatus.classList.remove('offline-progress');offlineStatus.style.removeProperty('--download-progress');updateOfflinePackUi();return offlineTranslator}catch(error){offlineStatus.classList.remove('offline-progress');offlineStatus.textContent=navigator.onLine?'Не вдалося завантажити пакет. Спробуй ще раз.':'Для першого завантаження потрібен інтернет.';throw error}finally{offlineButton.disabled=false;offlineLoading=null}})();return offlineLoading
}
offlineButton.onclick=async()=>{try{await loadOfflineTranslator(true);toast('Офлайн-пакет готовий')}catch(error){console.error(error);toast('Не вдалося завантажити мовний пакет')}};
const onlineGoogleTranslate=googleTranslate;
googleTranslate=async function(text,target){if(target==='uk'&&isProbablyUkrainian(text))return text;if(offlineToggle.checked&&target==='uk'){if(localStorage.getItem('offlineEnUkReady')!=='true'&&!navigator.onLine)throw Error('offline_pack_missing');const translator=await loadOfflineTranslator(false),parts=text.match(/[\s\S]{1,420}(?:\s|$)/g)||[text],translatedParts=[];for(const part of parts){const result=await translator(part,{max_new_tokens:512});translatedParts.push(result?.[0]?.translation_text||'')}return translatedParts.join(' ')}return onlineGoogleTranslate(text,target)};

function isProbablyUkrainian(text){const letters=(text.match(/[а-яіїєґ]/gi)||[]).length;if(letters<8)return false;if(/[іїєґ]/i.test(text))return true;if(/[ыэъё]/i.test(text))return false;return /\b(та|що|це|для|коли|який|яка|було|його|вона|вони|мене|тебе|україн)/i.test(text)}
translated=async function(text){
  if(!$('#translateToggle').checked)return text;
  const book=state.books[state.current],target=$('#speechLanguage').value.split('-')[0],key=`${state.index}:${target}`;book.translations=book.translations||{};
  if(target==='uk'&&isProbablyUkrainian(text)){delete book.translations[key];return text}
  if(book.translations[key])return book.translations[key];toast('Перекладаю мовою озвучення…');const endpoint=$('#translateEndpoint').value.trim();
  try{let result;if(endpoint){const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({q:text,source:'auto',target,format:'text'})});if(!response.ok)throw Error();result=(await response.json()).translatedText}else result=await googleTranslate(text,target);book.translations[key]=result;save();return result}catch(error){toast(error?.message==='offline_pack_missing'?'Спочатку завантаж офлайн-пакет':'Не вдалося перекласти. Перевір з’єднання або сервіс.');throw Error('translation_failed')}
};
